### ISSUE TITLE
Flaky tests (triggered in autopkgtests on armhf)

### ISSUE THREAD

**Issue by didrocks** [canonical/ubuntu-pro-for-wsl#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Some tests triggered races on armhf, which was a very slow VM in autopkgtests. Worth checking them so that we don’t get a pass and have to rerun the tests everytimes we are failing.

I considered them as flaky as they are all timing related.

### Steps to reproduce it

Test list failing:

https://objectstorage.prodstack5.canonical.com/swift/v1/AUTH_0f9aae918d5b4744bf7b827671c86842/autopkgtest-noble/noble/armhf/w/wsl-pro-service/20240202_051125_c3828@/log.gz

```sh
768s --- FAIL: TestReconnection (0.00s)
768s     --- FAIL: TestReconnection/Success_connecting_after_failing_to_connect (79.91s)
768s     --- FAIL: TestReconnection/Success_connecting_after_previous_connection_dropped (86.16s)


768s --- FAIL: TestServeAndQuit (0.12s)
768s     --- FAIL: TestServeAndQuit/Success_with_graceful_quit (74.30s)
768s     --- FAIL: TestServeAndQuit/Success_with_forceful_quit (98.06s)
768s     --- FAIL: TestServeAndQuit/Success_with_double_quit (100.96s)


1124s --- FAIL: TestReconnection (0.00s)
1124s     --- FAIL: TestReconnection/Success_connecting_after_previous_connection_dropped (100.70s)
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by CarlosNihelton** [comment]
Closed by #873 .
