### ISSUE TITLE
Issue: Negative port may be returned by net.SplitHostPort in the Ubuntu service implementation.

### ISSUE THREAD

**Issue by iosifache** [canonical/ubuntu-pro-for-wsl#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

The latest version integrated the following changes in `wsl-pro-service/controlstream/controlstream.go`:

```go
-	fields := strings.Split(string(addr), ":")
-	if len(fields) == 0 {
-		// Avoid a panic. As far as I know, there is no way of triggering this,
-		// but we may as well protect against it.
-		return "", fmt.Errorf("could not extract port out of address %q", addr)
+	_, port, err := net.SplitHostPort(string(addr))
+	if err != nil {
+		return "", fmt.Errorf("could not parse port from %q: %v", addr, err)
 	}
-	port := fields[len(fields)-1]
```

The `net.SplitHostPort` function returns any string after `:`. For instance, `fmt.Println(net.SplitHostPort("127.0.0.1:-19"))` results in the string `127.0.0.1 -19 <nil>`. Given this, the returned port may be a string representing a negative value.

As no check is conducted in the `address` function, subsequent operations in the Ubuntu service may fail due to this unexpected negative port number. Please consider introducing an assertion for the port to be a positive value.

Many thanks!

### Steps to reproduce it

N/A

### Ubuntu System information

N/A

### Installed versions

`v0.1.2`

### Additional information

As discussed with @didrocks, this issue is sufficiently clear and doesn't require system logs. Hence, it was reported directly in this repository.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by EduardGomezEscandell** [comment]
Thanks for your report! It is fixed now :D
