### ISSUE TITLE
Flaky test  TestTaskProcessing/Error_when_the_distro_is_not_registered

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-pro-for-wsl#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

https://github.com/canonical/ubuntu-pro-for-wsl/pull/652

Test  TestTaskProcessing/Error_when_the_distro_is_not_registered fails with and without race detector.

### Steps to reproduce it

CI

### Installed versions

* Windows version: *Run cmd /c ver*
* WSL version: *wsl --status*
* Windows application version: Open Pro for Windows GUI, check version in status bar.
* WSL distribution: Name of the Ubuntu distribution you are using
* WSL OS: (`/etc/os-release`) in the wsl instance
* ubuntu wsl service version: (`apt policy wsl-pro-service` output)

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by EduardGomezEscandell** [comment]
Thanks for the report. This is a known flaky test. Just re-run it for now. We'll get to it in the future.

**Comment by jibel** [comment]
I re-ran it 3 times and it fails on https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/8186587564/job/22385247887?pr=666 too.

**Comment by EduardGomezEscandell** [comment]
I'll have to focus on it then
