### ISSUE TITLE
Replace "FQDN" by "Landscape server address"

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-pro-for-wsl#801]
Replace Landscape FQDN by Landscape server address

![Capture d'écran 2024-06-14 113129](https://github.com/canonical/ubuntu-pro-for-wsl/assets/1928546/bfa9b4bf-e0bd-4fc4-8a37-99b6e7d1b2a7)

**Comment by CarlosNihelton** [comment]
Closed by #820
