### ISSUE TITLE
Ubuntu Pro app doesn’t reconnect to Landscape when the connection drops

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-pro-for-wsl#803]
Pro App v0.1.4-278-g6bc9409e

 # Test Case
1. Disconnect the network to the landscape server
2. Verify that the agent loses the connection
3. Reconnect 
4. Verify that the agent reconnects

# Actual result
1. It doesn't reconnect.

**Comment by CarlosNihelton** [comment]
I investigated this issue together with a similar symptom of the agent not reconnecting to Landscape after a reboot.
Testing with recent branches I couldn’t reproduce both issues anymore. I noticed that logs are quite silent by default and changing the configuration inside `%USERPROFILE%\.ubuntupro` didn't change that, which could contribute to one’s idea that the agent is doing nothing in the background, hence https://github.com/canonical/ubuntu-pro-for-wsl/pull/901 . Of course that doesn’t explain the issue reported.

To test it I installed UP4W locally built from the following branches:
- https://github.com/canonical/ubuntu-pro-for-wsl/pull/901 
- https://github.com/canonical/ubuntu-pro-for-wsl/pull/896 
- and the previous main (before the merge of those).

I ran the GUI and configured a Pro token and Landscape configuration, registered between 1 and 3 WSL instances and made sure they all showed up in the dashboard. With that setup:

- I rebooted the VM and monitored UP4W verbose logs and the Landscape dashboard: communication was always restablished.

- I interrupted the communication by disconnecting the Windows VM network adapter. After reconnecting the adapter, UP4W agent and Landscape restablished communication as expected.

- I interrupted the communication by rebooting the Landscape Server VM. Communication was eventually restablished.

After not being able to reproduce this issue, I'm closing it.
