### ISSUE TITLE
Filter *.pem files in the file chooser

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-pro-for-wsl#878]
On the Landscape configuration page, the certificate field needs a pem file and even provides as example c:\landscape.pem but the file chooser is set to display *.*. It should filter only *.pem by default with *.* as another option.

![image](https://github.com/user-attachments/assets/f5c7caf8-43dc-430b-9f1b-9264959e52c2)

**Comment by ashuntu** [comment]
It looks like the [`file_picker`](https://pub.dev/packages/file_picker) package we use doesn't support a "default" option and a fallback option at the same time. Either we allow any files to be picked or limit to a set of file extensions (`'cer', 'crt', 'der', 'pem'`).

**Comment by CarlosNihelton** [comment]
Let's limit the set of file extensions as said above. The worse thing that can happen is a missing element in the set, for which someone will open a bug and we'll add it accordingly.
