### ISSUE TITLE
Issue: Cloud init receives Windows-style file path for Landscape client `ssl_public_key`

### ISSUE THREAD

**Issue by wck0** [canonical/ubuntu-pro-for-wsl#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

When installing a WSL image using cloud init material, the ssl_public_key is injected to the cloud init `user-data.txt` file as a Windows-style file path on the created WSL image. This prevents the WSL image from registering with Landscape.

### Steps to reproduce it

1. Install and configure Landscape Quickstart Server `24.10~beta.7-0landscape0`, set a registration key, and enable auto-enrollment.
2. Create a `cloud_init.yaml` file with the following contents:
```yaml
#cloud-config
snap:
  commands:
    0: [install, moon-buggy]
apt:
  preserve_sources_list: true
  sources:
    landscape-beta.list:
      source: "ppa:landscape/self-hosted-beta"
package_update: true
package_upgrade: true
packages:  ["landscape-client"]
```
3. Create a child instance profile associated with the tag `windows` using Ubuntu-24.04 and the above cloud init material:
```bash
export JWT=$(http POST localhost:9080/login email=your_user@example.com password=your_password | jq -r ".token")
http POST localhost:9080/api/v2/child-instance-profiles Authorization:"Bearer $JWT" title="My Ubuntu" description=demo image_name=Ubuntu-24.04 cloud_init_contents=$(base64 --wrap=0 < ~/cloud_init.yaml) tags=windows
```
4. Register a Windows host with Landscape, setting the `ssl_public_key` to be the Windows-style path to the downloaded Landscape Server cert.
5. In Landscape, add the `windows` tag to the registered Windows host.
6. Wait for the activity to complete and the WSL instance to be installed on the Windows host.
7. Check `/var/lib/cloud/instance/user-data.txt` and see that `landscape.client.ssl_public_key` has a Windows style file path.
8. Check `/etc/landscape/client.conf` and see that `client.ssl_public_key` has a Windows style file path.

### Installed versions

* Windows version: *Run cmd /c ver*
OS Name             : Microsoft Windows 11 Pro
OS Version          : 10.0.22621 N/A Build 22621
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 9/9/2024, 4:21:45 PM
System Manufacturer : Microsoft Corporation
System Model        : Virtual Machine
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 3 Hotfix(s) Installed.,[01]: KB5042099,[02]: KB5041585,[03]: KB5041584

* WSL version: *wsl --status*
Default Distribution: Ubuntu-24.04
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.

* Windows application version: Open Pro for Windows GUI, check version in status bar.
v0.1.4-626-g5cc9fcd4-dirty

* WSL distribution: Name of the Ubuntu distribution you are using
Ubuntu-24.04

* WSL OS: (`/etc/os-release`) in the wsl instance

Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

* ubuntu wsl service version: (`apt policy wsl-pro-service` output)
wsl-pro-service:
  Installed: 0.1.5~ppa5~24.04.1
  Candidate: 0.1.5~ppa5~24.04.1
  Version table:
 *** 0.1.5~ppa5~24.04.1 500
        500 http://ppa.launchpad.net/ubuntu-wsl-dev/ppa/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
     0.1.4 500
        500 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages

### System logs

time=2024-09-09T18:02:19Z level=debug msg=Landscape: sending info: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Token:C1*************************wg Uid:390fabebed3e48ae91c3cf0dfbc36cb0 Hostname:CanonicalLtd Instances:[] AccountName:standalone RegistrationKey:0xc000076250 DefaultInstanceId:0xc00040e8d0}
time=2024-09-09T18:05:21Z level=info msg=Landscape: received command Install (id: "Ubuntu-24.04")
time=2024-09-09T18:05:21Z level=debug msg=Landscape: received command Install. Target: Ubuntu-24.04
time=2024-09-09T18:07:43Z level=info msg=New connection from client [[Ubuntu-24.04:382475]]
time=2024-09-09T18:07:43Z level=debug msg=[[Ubuntu-24.04:382475]] New request /agentapi.WSLInstance/LandscapeConfigCommands
time=2024-09-09T18:07:43Z level=info msg=New connection from client [[Ubuntu-24.04:389993]]
time=2024-09-09T18:07:43Z level=debug msg=[[Ubuntu-24.04:389993]] New request /agentapi.WSLInstance/Connected
time=2024-09-09T18:07:43Z level=info msg=New connection from client [[Ubuntu-24.04:398133]]
time=2024-09-09T18:07:43Z level=debug msg=[[Ubuntu-24.04:398133]] New request /agentapi.WSLInstance/ProAttachmentCommands
time=2024-09-09T18:07:44Z level=debug msg=[[Ubuntu-24.04:389993]] Requesting with parameters: WslName: Ubuntu-24.04, Id: ubuntu, VersionId: 24.04, PrettyName: Ubuntu 24.04.1 LTS, ProAttached: false, Hostname: CanonicalLtd
time=2024-09-09T18:07:44Z level=debug msg=[[Ubuntu-24.04:389993]] Database: cache miss, creating "Ubuntu-24.04" and adding it to the database
time=2024-09-09T18:07:44Z level=debug msg=[[Ubuntu-24.04:398133]] Requesting with parameters: Data: 0xc000370450
time=2024-09-09T18:07:44Z level=debug msg=[[Ubuntu-24.04:382475]] Requesting with parameters: Data: 0xc000370410
time=2024-09-09T18:07:44Z level=debug msg=Distro "Ubuntu-24.04": starting task processing
time=2024-09-09T18:07:44Z level=debug msg=[[Ubuntu-24.04:389993]] connection to Linux-side WSL service established
time=2024-09-09T18:07:44Z level=debug msg=Landscape: sending info: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Token:C1*************************wg Uid:390fabebed3e48ae91c3cf0dfbc36cb0 Hostname:CanonicalLtd Instances:[id:"Ubuntu-24.04" name:"CanonicalLtd" version_id:"24.04" instance_state:Running] AccountName:standalone RegistrationKey:0xc00022c160 DefaultInstanceId:0xc00020a800}
time=2024-09-09T18:10:25Z level=info msg=Landscape: completed command Install (id: "Ubuntu-24.04")
time=2024-09-09T18:10:25Z level=debug msg=Landscape: sending info: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Token:C1*************************wg Uid:390fabebed3e48ae91c3cf0dfbc36cb0 Hostname:CanonicalLtd Instances:[id:"Ubuntu-24.04" name:"CanonicalLtd" version_id:"24.04" instance_state:Running] AccountName:standalone RegistrationKey:0xc0002bc070 DefaultInstanceId:0xc000510290}
time=2024-09-09T18:11:52Z level=info msg=[[Ubuntu-24.04:389993]] Error sent to client: could not receive info: context canceled
time=2024-09-09T18:11:52Z level=debug msg=[[Ubuntu-24.04:389993]] Request /agentapi.WSLInstance/Connected done
time=2024-09-09T18:11:52Z level=debug msg=[[Ubuntu-24.04:389993]] Requesting with parameters: WslName: , Id: , VersionId: , PrettyName: , ProAttached: false, Hostname: 
time=2024-09-09T18:11:52Z level=warning msg=[[Ubuntu-24.04:389993]] couldn't send logs to client
time=2024-09-09T18:11:52Z level=debug msg=[[Ubuntu-24.04:398133]] Request /agentapi.WSLInstance/ProAttachmentCommands done
time=2024-09-09T18:11:52Z level=debug msg=[[Ubuntu-24.04:382475]] Request /agentapi.WSLInstance/LandscapeConfigCommands done
time=2024-09-09T18:11:52Z level=debug msg=Landscape: sending info: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Token:C1*************************wg Uid:390fabebed3e48ae91c3cf0dfbc36cb0 Hostname:CanonicalLtd Instances:[id:"Ubuntu-24.04" name:"CanonicalLtd" version_id:"24.04"] AccountName:standalone RegistrationKey:0xc0002bc8e0 DefaultInstanceId:0xc000370250}
time=2024-09-09T18:15:52Z level=info msg=New connection from client [[Ubuntu-24.04:954359]]
time=2024-09-09T18:15:52Z level=debug msg=[[Ubuntu-24.04:954359]] New request /agentapi.WSLInstance/LandscapeConfigCommands
time=2024-09-09T18:15:52Z level=info msg=New connection from client [[Ubuntu-24.04:315382]]
time=2024-09-09T18:15:52Z level=debug msg=[[Ubuntu-24.04:315382]] New request /agentapi.WSLInstance/ProAttachmentCommands
time=2024-09-09T18:15:52Z level=info msg=New connection from client [[Ubuntu-24.04:739264]]
time=2024-09-09T18:15:52Z level=debug msg=[[Ubuntu-24.04:739264]] New request /agentapi.WSLInstance/Connected
time=2024-09-09T18:15:57Z level=debug msg=[[Ubuntu-24.04:954359]] Requesting with parameters: Data: 0xc00020a420
time=2024-09-09T18:15:57Z level=debug msg=[[Ubuntu-24.04:739264]] Requesting with parameters: WslName: Ubuntu-24.04, Id: ubuntu, VersionId: 24.04, PrettyName: Ubuntu 24.04.1 LTS, ProAttached: true, Hostname: CanonicalLtd
time=2024-09-09T18:15:57Z level=debug msg=[[Ubuntu-24.04:315382]] Requesting with parameters: Data: 0xc000510050
time=2024-09-09T18:15:57Z level=debug msg=[[Ubuntu-24.04:739264]] Database: cache hit. Overwriting properties for "Ubuntu-24.04"
time=2024-09-09T18:15:57Z level=debug msg=[[Ubuntu-24.04:739264]] connection to Linux-side WSL service established
time=2024-09-09T18:15:57Z level=debug msg=Landscape: sending info: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Token:C1*************************wg Uid:390fabebed3e48ae91c3cf0dfbc36cb0 Hostname:CanonicalLtd Instances:[id:"Ubuntu-24.04" name:"CanonicalLtd" version_id:"24.04" instance_state:Running] AccountName:standalone RegistrationKey:0xc0000d2f70 DefaultInstanceId:0xc00020ac70}

root@CanonicalLtd:/mnt/c/Users/wck0/Downloads/UbuntuProForWSL_0.1.4.0_Test# journalctl -u wsl-pro.service
Sep 09 18:07:38 CanonicalLtd systemd[1]: Starting wsl-pro.service - Bridge to Ubuntu Pro agent on Windows...
Sep 09 18:07:39 CanonicalLtd wsl-pro-service[266]: INFO Starting WSL Pro Service version v0.1.4-581-g069870c4-dirty
Sep 09 18:07:42 CanonicalLtd wsl-pro-service[266]: WARNING Could not ensure valid Landscape configuration: could not en>
Sep 09 18:07:42 CanonicalLtd wsl-pro-service[266]:     Stdout: An account name and computer title are required.
Sep 09 18:07:42 CanonicalLtd wsl-pro-service[266]:     Stderr: Aborting Landscape configuration
Sep 09 18:07:43 CanonicalLtd systemd[1]: Started wsl-pro.service - Bridge to Ubuntu Pro agent on Windows.
-- Boot d20458b867254fbaa50df798ee9fe1dc --
Sep 09 18:15:41 CanonicalLtd systemd[1]: Starting wsl-pro.service - Bridge to Ubuntu Pro agent on Windows...
Sep 09 18:15:42 CanonicalLtd wsl-pro-service[249]: INFO Starting WSL Pro Service version v0.1.4-581-g069870c4-dirty
Sep 09 18:15:52 CanonicalLtd systemd[1]: Started wsl-pro.service - Bridge to Ubuntu Pro agent on Windows.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by CarlosNihelton** [comment]
Well, that's by design. There is no correct way for UP4W to translate that path upfront, because the final destination is dependent on the configuration of each specific instance. So we rely on wsl-pro-service running inside the instance to fix the path and make Landscape client eventually connect. We don't have a better way to handle this at this point.
